version: '3.5'

services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'stocks'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'thndr'
            MYSQL_ROOT_PASSWORD: 'thndr'
        ports:
            - '3306:3306'
        expose:
            - '3306'

    vernemq:
        environment:
            - DOCKER_VERNEMQ_ACCEPT_EULA=yes
            - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
            - MQTT_TOPIC=thndr-trading
        image: erlio/docker-vernemq
        ports:
            - '1883:1883'
        expose:
            - '1883'

    streamer:
        environment:
            - MQTT_HOST=vernemq
            - MQTT_PORT=1883
            - MQTT_TOPIC=thndr-trading
        image: thndr/streamer:0.2
        depends_on:
            - vernemq


