apiVersion: apps/v1
kind: Deployment
metadata:
  name: vernemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vernemq
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vernemq
    spec:
      containers:
        - name: vernemq
          image: erlio/docker-vernemq
          ports:
            - containerPort: 1883
              protocol: TCP
          env:
            - name: DOCKER_VERNEMQ_ACCEPT_EULA
              value: 'yes'
            - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
              value: 'on'
            - name: MQTT_TOPIC
              value: thndr-trading
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600